# Generated by Django 4.2.3 on 2023-07-18 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User name')),
                ('second_name', models.CharField(max_length=50, verbose_name='User second name')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='User surname')),
                ('date_birth', models.DateField(verbose_name='Date of user birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User profile')),
            ],
        ),
    ]
