# Generated by Django 4.2.3 on 2023-07-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_contact_contact_uniqueness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job description')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(blank=True, help_text='Leave blank if currently employed', null=True, verbose_name='End date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='user.profile')),
            ],
            options={
                'verbose_name_plural': ('Employments',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255, verbose_name='Education institution name')),
                ('degree', models.CharField(max_length=30, verbose_name='Degree or level of education')),
                ('speciality', models.CharField(max_length=255, verbose_name='Speciality of learning')),
                ('date_start', models.DateField(verbose_name='Date of education beginning')),
                ('date_end', models.DateField(blank=True, help_text='Enter date of education was ended, or leve blank if currently learning', null=True, verbose_name='Date of education ended')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_set', to='user.profile')),
            ],
            options={
                'verbose_name_plural': ('Education',),
            },
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(fields=('profile', 'institution', 'degree', 'speciality'), name='Education unique constraint'),
        ),
    ]
