# Generated by Django 4.2.3 on 2023-07-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_date_birth_employment_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='residence_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Current live place'),
        ),
    ]
