# Generated by Django 4.2.3 on 2023-07-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_residence_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-date_end'], 'verbose_name_plural': ('Education',)},
        ),
    ]
