# Generated by Django 4.2.3 on 2023-07-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_education_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='Contact uniqueness',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='link',
            new_name='data',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('profile', 'type', 'data'), name='Contact uniqueness'),
        ),
    ]
