# Generated by Django 4.2.3 on 2023-07-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_contact_contact_uniqueness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_link',
        ),
        migrations.AlterField(
            model_name='contact',
            name='data',
            field=models.CharField(max_length=200, verbose_name='Contact data (link, nickname, etc.)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('phone', 'Phone number'), ('email', 'Email address'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('github', 'Github'), ('linkedin', 'Linkedin')], max_length=30, verbose_name='Contact type'),
        ),
    ]
