# Generated by Django 4.2.3 on 2023-07-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_contact_is_link_alter_contact_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course name')),
                ('certificate', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Coursee certificate')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user.profile')),
            ],
        ),
    ]
