# Generated by Django 4.2.3 on 2023-07-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Course certificate'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
                ('link', models.URLField(blank=True, max_length=100, null=True, verbose_name='Link to project')),
                ('source', models.URLField(blank=True, max_length=100, null=True, verbose_name='Link to project source')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user.profile')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='Project uniqueness'),
        ),
    ]
