# Generated by Django 4.2.3 on 2023-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_course_options_alter_course_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description of project'),
        ),
    ]
