# Generated by Django 4.2.3 on 2023-07-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Link to hosted project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Link to project repository'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('link__isnull', True), ('link__iexact', ''), _negated=True), models.Q(('source__isnull', True), ('source__iexact', ''), _negated=True), _connector='OR'), name='Either link or source code should be specified'),
        ),
    ]
