# Generated by Django 4.2.3 on 2023-07-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_project_link_alter_project_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='Either link or source code should be specified',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('link__iexact', ''), ('link__isnull', True), _negated=True), models.Q(('source__iexact', ''), ('source__isnull', True), _negated=True), _connector='OR'), name='Either link or source code should be specified'),
        ),
    ]
