# Generated by Django 4.2.3 on 2023-07-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_project_either_link_or_source_code_should_be_specified_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='Either link or source code should be specified',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('link__isnull', True), ('link__iexact', ''), _connector='OR'), _negated=True), models.Q(models.Q(('source__isnull', True), ('source__iexact', ''), _connector='OR'), _negated=True), _connector='OR'), name='Either link or source code should be specified'),
        ),
    ]
