# Generated by Django 4.2.3 on 2023-07-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_project_either_link_or_source_code_should_be_specified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of project'),
        ),
    ]
