# Generated by Django 4.2.3 on 2023-07-26 12:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0018_alter_education_date_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='CV name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Image')),
                ('info', models.TextField(verbose_name='Personal information')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Extra information')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='user.profile', verbose_name='User cv')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hard', 'Hard skill'), ('soft', 'Soft skill')], max_length=10, verbose_name='Type of skill')),
                ('name', models.CharField(max_length=255, verbose_name='Skill name')),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level of possessing skill in grade from 1 to 10')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Skill description')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv.cv', verbose_name='Certain skill')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('cv', 'name'), name='Unique skill name'),
        ),
        migrations.AddConstraint(
            model_name='cv',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='Unique cv name constraint'),
        ),
    ]
