# Generated by Django 4.2.3 on 2023-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='position',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Pretended position'),
        ),
    ]
