# Generated by Django 4.2.3 on 2023-07-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='position',
        ),
    ]
