# Generated by Django 4.2.3 on 2023-07-19 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Skill description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level of possesing skill in grade from 1 to 10'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='defaultskill', max_length=255, verbose_name='Skill name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('hard', 'Hard skill'), ('soft', 'Soft skill')], default='hard', max_length=10, verbose_name='Type of skill'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='Unique portfolio name constraint'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('portfolio', 'name'), name='Unique skill name'),
        ),
    ]
