# Generated by Django 4.2.3 on 2023-07-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_skill_options_skill_description_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='Extra informatioon'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='info',
            field=models.TextField(default='defaultinfo', verbose_name='Personal information'),
            preserve_default=False,
        ),
    ]
