# Generated by Django 4.2.3 on 2023-07-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_course_options_alter_course_certificate_and_more'),
        ('portfolio', '0003_portfolio_extra_info_portfolio_info'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portfolio',
            name='Unique portfolio name constraint',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profile',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='user.profile', verbose_name='User portfolio'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='Unique portfolio name constraint'),
        ),
    ]
