# Generated by Django 4.2.3 on 2023-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('A1', '(A1) Beginner'), ('A2', '(A2) Elementary'), ('B1', '(B1) Intermediate'), ('B2', '(B2) Upper Intermediate'), ('C1', '(C1) Advanced'), ('C2', '(C2) Proficient'), ('native', 'Native')], max_length=10, verbose_name='Level of knowing the language'),
        ),
    ]
