# Generated by Django 4.2.3 on 2023-07-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_alter_language_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Languages'},
        ),
    ]
