# Generated by Django 4.2.3 on 2023-07-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_alter_language_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='user',
            new_name='profile',
        ),
    ]
